name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ganti kalau branch bukan "main"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # ini karena index.html dan assets langsung di root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
